name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted, linux, x64]

    strategy:
      matrix:
        node-version: [20.x] # Use stable LTS version

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build the app (if applicable)
      run: npm run build --if-present

    - name: Start app with PM2
      run: |
        echo "Starting PM2 process..."
        FILE="server.js"
        if [ ! -f "$FILE" ]; then
          FILE="index.js"
        fi

        if [ ! -f "$FILE" ]; then
          echo " Error: No entry file found (server.js or index.js)"
          exit 1
        fi

        # Restart app if already running, else start fresh
        pm2 describe backend > /dev/null && pm2 restart backend --update-env || pm2 start $FILE --name backend

        pm2 save
