# This workflow installs dependencies, builds the app, and starts the server with PM2 on a self-hosted runner.

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted, linux, x64]

    strategy:
      matrix:
        node-version: [22.x] # Make sure Node.js 22 is actually supported on your system

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build the app (if applicable)
      run: npm run build --if-present

    - name: Start app with PM2
      run: |
        pm2 delete all || true
        pm2 start server.js --name backend
        pm2 save
